package com.achiva.model.blogs.domain;
// Generated Dec 13, 2017 6:59:07 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Blogstopic generated by hbm2java
 */
@Entity
@Table(name = "blogstopic")
public class BlogsTopic implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4364896774935092217L;
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id")
	private Integer id;

	private String url;

	@Column(name = "Created_By")
	private String createdBy;

	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
	private Date createdOn;

	private Integer noOfVisit;

	private String updatedBy;

	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
	private Date updatedOn;

	private String active;

	private String blogsContains;
	
	@Column(name="Display_Ranking")
	private int displayRanking;
	
	@Column(name="Created_By_Moblie_No")
	private String createdByMoblieNo;
	
	@Column(name="Created_By_Email_Id")
	private String createdByEmailId;
	
	@Column(name="Created_By_FBId")
	private String createdByFBId;
	
	@Column(name="Created_By_Google_Id")
	private String createdByGoogleId;
	
	
	@OneToMany(mappedBy = "blogstopic", fetch = FetchType.LAZY)
	@JsonManagedReference
	private Set<TopicGallery> topicgalleries = new HashSet<>(0);
	
	@OneToMany(mappedBy = "blogstopic", fetch = FetchType.LAZY)
	@JsonManagedReference
	private Set<TopicComments> topiccommentses = new HashSet<>(0);
	
	@OneToMany(mappedBy = "blogstopic", fetch = FetchType.LAZY)
	@JsonManagedReference
	private Set<TopicHistory> topichistories = new HashSet<>(0);

	public BlogsTopic() {
	}

	public BlogsTopic(String url) {
		this.url = url;
	}

	public BlogsTopic(String url, String blogsContains, String createdBy, Date createdOn, Integer noOfVisit, String updatedBy, Date updatedOn, String active,
			Set<TopicGallery> topicgalleries, Set<TopicComments> topiccommentses, Set<TopicHistory> topichistories) {
		this.url = url;
		this.blogsContains = blogsContains;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.noOfVisit = noOfVisit;
		this.updatedBy = updatedBy;
		this.updatedOn = updatedOn;
		this.active = active;
		this.topicgalleries = topicgalleries;
		this.topiccommentses = topiccommentses;
		this.topichistories = topichistories;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getBlogsContains() {
		return this.blogsContains;
	}

	public void setBlogsContains(String blogsContains) {
		this.blogsContains = blogsContains;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public Integer getNoOfVisit() {
		return this.noOfVisit;
	}

	public void setNoOfVisit(Integer noOfVisit) {
		this.noOfVisit = noOfVisit;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

		
	/**
	 * @return the displayRanking
	 */
	public int getDisplayRanking() {
		return displayRanking;
	}

	/**
	 * @param displayRanking the displayRanking to set
	 */
	public void setDisplayRanking(int displayRanking) {
		this.displayRanking = displayRanking;
	}

	
	
	
	/**
	 * @return the createdByMoblieNo
	 */
	public String getCreatedByMoblieNo() {
		return createdByMoblieNo;
	}

	/**
	 * @param createdByMoblieNo the createdByMoblieNo to set
	 */
	public void setCreatedByMoblieNo(String createdByMoblieNo) {
		this.createdByMoblieNo = createdByMoblieNo;
	}

	/**
	 * @return the createdByEmailId
	 */
	public String getCreatedByEmailId() {
		return createdByEmailId;
	}

	/**
	 * @param createdByEmailId the createdByEmailId to set
	 */
	public void setCreatedByEmailId(String createdByEmailId) {
		this.createdByEmailId = createdByEmailId;
	}

	/**
	 * @return the createdByFBId
	 */
	public String getCreatedByFBId() {
		return createdByFBId;
	}

	/**
	 * @param createdByFBId the createdByFBId to set
	 */
	public void setCreatedByFBId(String createdByFBId) {
		this.createdByFBId = createdByFBId;
	}

	/**
	 * @return the createdByGoogleId
	 */
	public String getCreatedByGoogleId() {
		return createdByGoogleId;
	}

	/**
	 * @param createdByGoogleId the createdByGoogleId to set
	 */
	public void setCreatedByGoogleId(String createdByGoogleId) {
		this.createdByGoogleId = createdByGoogleId;
	}

	public Set<TopicGallery> getTopicgalleries() {
		return this.topicgalleries;
	}

	public void setTopicgalleries(Set<TopicGallery> topicgalleries) {
		this.topicgalleries = topicgalleries;
	}

	public Set<TopicComments> getTopiccommentses() {
		return this.topiccommentses;
	}

	public void setTopiccommentses(Set<TopicComments> topiccommentses) {
		this.topiccommentses = topiccommentses;
	}

	public Set<TopicHistory> getTopichistories() {
		return this.topichistories;
	}

	public void setTopichistories(Set<TopicHistory> topichistories) {
		this.topichistories = topichistories;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "BlogsTopic [id=" + id + ", url=" + url + ", createdBy=" + createdBy + ", createdOn=" + createdOn + ", noOfVisit=" + noOfVisit + ", updatedBy="
				+ updatedBy + ", updatedOn=" + updatedOn + ", active=" + active + ", blogsContains=" + blogsContains + ", topicgalleries=" + topicgalleries
				+ ", topiccommentses=" + topiccommentses + ", topichistories=" + topichistories + "]";
	}

}
