package com.achiva.model.blogs.domain;
// Generated Dec 13, 2017 6:59:07 AM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Commentsgallery generated by hbm2java
 */
@Entity
@Table(name="Commentsgallery")
public class CommentsGallery implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5743997258459682969L;
	
	@Id
	private Integer id;
	
	@ManyToOne
	@JoinColumn(name="CommentsId")
	@JsonBackReference
	private TopicComments topiccomments;
	
	private String imgUrl;
	private String imageTitle;
	private String imageDetails;
	private String active;

	public CommentsGallery() {
	}

	public CommentsGallery(TopicComments topiccomments, String imgUrl, String imageTitle, String imageDetails,
			String active) {
		this.topiccomments = topiccomments;
		this.imgUrl = imgUrl;
		this.imageTitle = imageTitle;
		this.imageDetails = imageDetails;
		this.active = active;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TopicComments getTopiccomments() {
		return this.topiccomments;
	}

	public void setTopiccomments(TopicComments topiccomments) {
		this.topiccomments = topiccomments;
	}

	public String getImgUrl() {
		return this.imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	public String getImageTitle() {
		return this.imageTitle;
	}

	public void setImageTitle(String imageTitle) {
		this.imageTitle = imageTitle;
	}

	public String getImageDetails() {
		return this.imageDetails;
	}

	public void setImageDetails(String imageDetails) {
		this.imageDetails = imageDetails;
	}

	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

}
