package com.achiva.model.blogs.domain;
// Generated Dec 13, 2017 6:59:07 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * Topichistory generated by hbm2java
 */
@Entity
@Table (name="topichistory")
public class TopicHistory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9217747377782398481L;
	
	@Id
	private Integer id;
	
	@ManyToOne
	@JoinColumn(name="Topic_Id", insertable=false, updatable=false)
	@JsonBackReference
	private BlogsTopic blogstopic;
	
	
	private String topicContains;
	private String updatedBy;
	
	@Temporal(TemporalType.TIMESTAMP)
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
	private Date updatedOn;
	

	@Column(name="topic_id")
	private Integer topicId;

	public TopicHistory() {
	}

	public TopicHistory(BlogsTopic blogstopic, String topicContains, String updatedBy, Date updatedOn) {
		this.blogstopic = blogstopic;
		this.topicContains = topicContains;
		this.updatedBy = updatedBy;
		this.updatedOn = updatedOn;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public BlogsTopic getBlogstopic() {
		return this.blogstopic;
	}

	public void setBlogstopic(BlogsTopic blogstopic) {
		this.blogstopic = blogstopic;
	}

	public String getTopicContains() {
		return this.topicContains;
	}

	public void setTopicContains(String topicContains) {
		this.topicContains = topicContains;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	/**
	 * @return the topicId
	 */
	public Integer getTopicId() {
		return topicId;
	}

	/**
	 * @param topicId the topicId to set
	 */
	public void setTopicId(Integer topicId) {
		this.topicId = topicId;
	}

	
}
