package com.achiva.model.blogs.domain;
// Generated Dec 13, 2017 6:59:07 AM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Topicgallery generated by hbm2java
 */
@Entity
@Table (name="topicgallery")
public class TopicGallery implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8958611321948303124L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name="id")
	private Integer id;
	
	@ManyToOne
	@JoinColumn(name="Topic_Id", insertable=false, updatable=false)
	@JsonBackReference
	private BlogsTopic blogstopic;
	
	
	@Column(name="Topic_Id")
	private Integer blogsTopicId;
	
	
	private String imgUrl;
	private String imageTitle;
	private String imageDetails;

	public TopicGallery() {
	}

	public TopicGallery(BlogsTopic blogstopic, String imgUrl) {
		this.blogstopic = blogstopic;
		this.imgUrl = imgUrl;
	}

	public TopicGallery(BlogsTopic blogstopic, String imgUrl, String imageTitle, String imageDetails) {
		this.blogstopic = blogstopic;
		this.imgUrl = imgUrl;
		this.imageTitle = imageTitle;
		this.imageDetails = imageDetails;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public BlogsTopic getBlogstopic() {
		return this.blogstopic;
	}

	public void setBlogstopic(BlogsTopic blogstopic) {
		this.blogstopic = blogstopic;
	}

	public String getImgUrl() {
		return this.imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	public String getImageTitle() {
		return this.imageTitle;
	}

	public void setImageTitle(String imageTitle) {
		this.imageTitle = imageTitle;
	}

	public String getImageDetails() {
		return this.imageDetails;
	}

	public void setImageDetails(String imageDetails) {
		this.imageDetails = imageDetails;
	}

}
