package com.achiva.model.blogs.dto;
// Generated Dec 13, 2017 6:59:07 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Topiccomments generated by hbm2java
 */

public class TopicCommentsDTO implements java.io.Serializable {
	
	private Integer id;
	
	private String commentsSub;
	private String commentsContains;
	private String commentsBy;
	
	private Date commentsOn;
	
	private String commentsByMoblieNo;
	private String commentsByEmailId;
	private String commentsByFbid;
	private String commentsByGoogleId;
	private String active;
	
	
	
	private Integer topicId;
	
	
	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	public String getCommentsSub() {
		return this.commentsSub;
	}

	public void setCommentsSub(String commentsSub) {
		this.commentsSub = commentsSub;
	}

	public String getCommentsContains() {
		return this.commentsContains;
	}

	public void setCommentsContains(String commentsContains) {
		this.commentsContains = commentsContains;
	}

	public String getCommentsBy() {
		return this.commentsBy;
	}

	public void setCommentsBy(String commentsBy) {
		this.commentsBy = commentsBy;
	}

	public Date getCommentsOn() {
		return this.commentsOn;
	}

	public void setCommentsOn(Date commentsOn) {
		this.commentsOn = commentsOn;
	}

	public String getCommentsByMoblieNo() {
		return this.commentsByMoblieNo;
	}

	public void setCommentsByMoblieNo(String commentsByMoblieNo) {
		this.commentsByMoblieNo = commentsByMoblieNo;
	}

	public String getCommentsByEmailId() {
		return this.commentsByEmailId;
	}

	public void setCommentsByEmailId(String commentsByEmailId) {
		this.commentsByEmailId = commentsByEmailId;
	}

	public String getCommentsByFbid() {
		return this.commentsByFbid;
	}

	public void setCommentsByFbid(String commentsByFbid) {
		this.commentsByFbid = commentsByFbid;
	}

	public String getCommentsByGoogleId() {
		return this.commentsByGoogleId;
	}

	public void setCommentsByGoogleId(String commentsByGoogleId) {
		this.commentsByGoogleId = commentsByGoogleId;
	}

	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	/**
	 * @return the topicId
	 */
	public Integer getTopicId() {
		return topicId;
	}

	/**
	 * @param topicId the topicId to set
	 */
	public void setTopicId(Integer topicId) {
		this.topicId = topicId;
	}

		
	
}
